#+TITLE: bekar
#+DATE: Saturday Jan 26 2015

#+STARTUP: showall

*bekar* is a /command line/ /static web-page generator/. It means
~Useless~ in some language, hoping it doesn't become so. This is
inspired from *git*, *[[https://github.com/moebiuseye/skf][skf]]* and *[[https://github.com/Ypnose/wswsh][wswsh]]*.

If you are asking why again /static web-page generator/ then this
might not be for you. It aims to integrate *org-mode* and *command-line*,
for generating a _very simple_ static page. Since, there are many
implementation which I found were either really complex, really simple
and dull or requires extensive lisp or ruby hacking which is kinda not
my thing.

*** THIS IS THE IDEA SKETCH
Still *UNDER DEVELOPMENT*, *GENERATOR DOESN'T WORK*

*YOU ARE WELCOMED TO HELP*

*** Setting up
=configure= can automatically check what you are missing.
**** Dependencies
- *emacs* : org-mode
- *bash*  : GNU sed, GNU awk


*** Install
    *TIP*: see =make= recipes for alternatives.

    #+BEGIN_SRC bash
      $ git clone https://github.com/rhoit/bekar-static-gen
      $ cd bekar-static-gen
      $ ./configure
      $ make
      $ sudo make install
    #+END_SRC

*** How to Use
    Features are still under development... 
    The following shows the architecture
    and design for now.

    #+BEGIN_SRC bash
      $ bekar --help
      bekar - A Static Page CLI Generator
       Usage: bekar <command> [OPTION(s)] [<args>]
              -c | --credits  Say hello to developers
              -h | --help     Display this message
       Commands:
           init    [PATH]     Create static pages source directory
           clone   [URL|PATH] Clone a templates.
           add     [FILE(s)]  Add the page to generation list
           rm      [FILE(s)]  Remove the page from generation list
           gen     [FILE(s)]  Generate a static page
           git                Integration with git
           version            Show version information
    #+END_SRC

**** Getting Started
     First initialize the generator to the directory.

     #+BEGIN_SRC bash
       $ bekar clone sample # skip it, if you want to set existing directory
       $ cd sample
       $ bekar init         # don't forget too see --help
       $ bekar add .        # add files to generation list
       $ bekar gen
     #+END_SRC

*** Hacking
    You might want to link it first, so changes can reflect directly
    without re-installation.

    #+BEGIN_SRC bash
      $ sudo make link
    #+END_SRC

    See =src/Makefiles= for sample tests.
